name: Package for macOS

on: [push]

jobs:
  package:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup macOS build environment
      run: |
        ./scripts/package/macos-setup.sh
        mkdir artifacts
      env:
        DISCID_VERSION: 0.6.2
        FPCALC_VERSION: 1.4.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        source bin/activate
        pip install -r requirements-macos.txt
    - name: Build macOS app
      run: |
        source bin/activate
        ./scripts/package/macos-package-app.sh
        mv dist/*.dmg artifacts/
    - name: Archive production artifacts
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: macos-builds
        path: artifacts/
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
