name: Package for Windows

on: [push]

jobs:
  package:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup Windows build environment
      run: |
        & .\scripts\package\win-setup.ps1 -DiscidVersion $Env:DISCID_VERSION -FpcalVersion $Env:FPCALC_VERSION
      env:
        DISCID_VERSION: 0.6.2
        FPCALC_VERSION: 1.4.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-build.txt
        pip install -r requirements-win.txt
    - name: Build Windows 10 app package
      run: |
        $Env:PATH += ";C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64"
        $Certificate = @(Get-ChildItem cert:\CurrentUser\My -codesign)[0]
        & .\scripts\package\win-package-appx.ps1 -BuildNumber $(git rev-list --count HEAD) -Certificate $Certificate
    - name: Build Windows installer
      if: always()
      run: |
        choco install nsis
        $Certificate = @(Get-ChildItem cert:\CurrentUser\My -codesign)[0]
        & .\scripts\package\win-package-installer.ps1 -BuildNumber $(git rev-list --count HEAD) -Certificate $Certificate
        dist\picard\fpcalc -version
    - name: Build Windows portable app
      if: always()
      run: |
        $Certificate = @(Get-ChildItem cert:\CurrentUser\My -codesign)[0]
        & .\scripts\package\win-package-portable.ps1 -BuildNumber $(git rev-list --count HEAD) -Certificate $Certificate
